version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  php7:
    build:
      context: ./php7
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app

  php8:
    build:
      context: ./php8
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app